// Code generated by MockGen. DO NOT EDIT.
// Source: online_payment_check.go

// Package resolver is a generated GoMock package.
package resolver

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	mssql "go.citilink.cloud/order/internal/order/payment/resolver/mssql"
	store_types "go.citilink.cloud/store_types"
)

// MockOnlinePaymentInfo is a mock of OnlinePaymentInfo interface.
type MockOnlinePaymentInfo struct {
	ctrl     *gomock.Controller
	recorder *MockOnlinePaymentInfoMockRecorder
}

// MockOnlinePaymentInfoMockRecorder is the mock recorder for MockOnlinePaymentInfo.
type MockOnlinePaymentInfoMockRecorder struct {
	mock *MockOnlinePaymentInfo
}

// NewMockOnlinePaymentInfo creates a new mock instance.
func NewMockOnlinePaymentInfo(ctrl *gomock.Controller) *MockOnlinePaymentInfo {
	mock := &MockOnlinePaymentInfo{ctrl: ctrl}
	mock.recorder = &MockOnlinePaymentInfoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOnlinePaymentInfo) EXPECT() *MockOnlinePaymentInfoMockRecorder {
	return m.recorder
}

// GetRegions mocks base method.
func (m *MockOnlinePaymentInfo) GetRegions(ctx context.Context) (map[store_types.SpaceId]*mssql.YandexPayShopData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegions", ctx)
	ret0, _ := ret[0].(map[store_types.SpaceId]*mssql.YandexPayShopData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegions indicates an expected call of GetRegions.
func (mr *MockOnlinePaymentInfoMockRecorder) GetRegions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegions", reflect.TypeOf((*MockOnlinePaymentInfo)(nil).GetRegions), ctx)
}
